package org.example.syntheakds;

import org.apache.commons.io.FileUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.LoggerContext;
import org.example.syntheakds.config.SyntheaKDSConfig;
import org.example.syntheakds.processing.ProcessingTask;
import org.example.syntheakds.processing.Processor;
import org.example.syntheakds.utils.Utils;
import org.mitre.synthea.engine.Generator;
import org.mitre.synthea.engine.Generator.GeneratorOptions;
import org.mitre.synthea.helpers.Config;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

public final class Main {

    private static final Logger logger = LogManager.getLogger(Main.class);

    private Main() {}

    public static void main(String[] args) throws IOException {
        configureLog4j2();

        logger.info("[#]Starting application ...");

        createDirs();

        logger.info("[#]Running Synthea ...");

        GeneratorOptions options = configureGeneratorOptions();
        Generator generator = new Generator(options);
        generator.run();
        logger.info("[#]Finished running Synthea.");

        logger.info("[#]Starting conversion ...");
        long start = System.currentTimeMillis() / 1000L;
        List<Path> paths = Utils.findFilesInDir(SyntheaKDSConfig.patDirPath, Utils.FileExtension.JSON);
        ProcessingTask task = new ProcessingTask();
        Processor<Path> processor = new Processor<>(paths, task);
        processor.run();
        long end = System.currentTimeMillis() / 1000L;
        long timeSpan = end - start;
        logger.info("[#]Finished conversion in {}m {}s.", (int) Math.floor(timeSpan / 60.0), timeSpan % 60);

        // Delete all files generated by Synthea
        FileUtils.cleanDirectory(SyntheaKDSConfig.patDirPath.toFile());
    }

    private static GeneratorOptions configureGeneratorOptions() {
        GeneratorOptions options = new GeneratorOptions();
        options.population = SyntheaKDSConfig.patientCount;
        options.clinicianSeed = SyntheaKDSConfig.clinicianSeed;
        options.referenceTime = SyntheaKDSConfig.referenceTime;
        options.endTime = SyntheaKDSConfig.endTime;
        options.threadPoolSize = SyntheaKDSConfig.threadPoolSize;
        options.seed = SyntheaKDSConfig.seed;
        options.state = SyntheaKDSConfig.state;

        Config.set("exporter.ccda.export", "false");
        Config.set("exporter.fhir.export", "true");
        Config.set("exporter.fhir_stu3.export", "false");
        Config.set("exporter.fhir_dstu2.export", "false");
        Config.set("exporter.subfolders_by_id_substring", "false");
        Config.set("exporter.baseDirectory", SyntheaKDSConfig.tmpDirPath.toFile().getAbsolutePath());
        Config.set("generate.database_type", "none");
        Config.set("generate.only_dead_patients", "false");
        Config.set("generate.only_alive_patients", "true");
        Config.set("exporter.use_uuid_filenames", "true");
        return options;
    }

    /**
     * Sets Log4j2 config file location. Works inside jar too.
     */
    private static void configureLog4j2() {
        Path configFilePath = Paths.get("config", "log4j2.xml");
        LoggerContext context = (LoggerContext) LogManager.getContext(false);
        context.setConfigLocation(Utils.findResourceURI(configFilePath));
    }

    private static void createDirs() {
        logger.debug("Creating output directories ...");
        java.io.File outputDir = SyntheaKDSConfig.outputDirPath.toFile();
        if (!outputDir.exists()) outputDir.mkdirs();
        SyntheaKDSConfig.tmpDirPath.toFile().mkdirs();
        SyntheaKDSConfig.kdsDirPath.toFile().mkdirs();
        logger.debug("Created output directories.");
    }
}
